### ISSUE TITLE
subsonic filter

### ISSUE THREAD

**Issue by alekksander** [mudlord/foobar2000#2]
please implement subsonic filter (cut below 20, or 25 etc…)
i've seen requests for this one on forums, so it's not just me ;)

**Comment by mudlord** [comment]
Once my roadmap for 0.20 is done, I don't see why not :smile:

**Comment by alekksander** [comment]
thank You :)

**Comment by alekksander** [comment]
bumpalooo…

**Comment by mudlord** [comment]
not sure if i am going to get around to this to be honest D:

**Comment by alekksander** [comment]
why is that if i may ask? i think there is high demand for this judging on google's results for „subsonic filter foobar”. plenty of people need to cut out what's distorting their beautiful music — including me :) is it hard to code, or there are other reasons…?

**Comment by mudlord** [comment]
other reasons, mainly being this plugin has been all about adding features that only I want to be in it. I wanted this to focus on DSP *effects* mainly, like pitch shift/echo/vibrato/reverb/phaser/distortion, etc.
